# Generated by Django 4.2.24 on 2025-10-05 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='vault_locked_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Verrouillé jusqu'à"),
        ),
        migrations.AddField(
            model_name='user',
            name='vault_pin',
            field=models.CharField(blank=True, help_text='Code à 6 chiffres pour accéder au coffre-fort', max_length=6, null=True, verbose_name='Code PIN Coffre-fort'),
        ),
        migrations.AddField(
            model_name='user',
            name='vault_pin_attempts',
            field=models.IntegerField(default=0, verbose_name='Tentatives PIN échouées'),
        ),
    ]
