# Generated by Django 4.2.24 on 2025-10-07 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_vault_locked_until_user_vault_pin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='vault_locked_until',
        ),
        migrations.RemoveField(
            model_name='user',
            name='vault_pin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='vault_pin_attempts',
        ),
    ]
