# Generated by Django 4.2.24 on 2025-10-26 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_vault_locked_until_remove_user_vault_pin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('doctor', 'Médecin'), ('technician', 'Technicien')], default='doctor', max_length=20, verbose_name='Rôle'),
        ),
    ]
