# Generated by Django 4.2.24 on 2025-10-26 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('technician', 'Technicien')], default='admin', max_length=20, verbose_name='Rôle'),
        ),
    ]
