# Generated by Django 4.2.24 on 2025-09-30 23:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deletion_type', models.CharField(choices=[('patient', 'Patient'), ('document', 'Document'), ('report', 'Rapport'), ('user', 'Utilisateur'), ('activity', 'Activité')], max_length=20, verbose_name="Type d'élément")),
                ('original_id', models.PositiveIntegerField(verbose_name='ID original')),
                ('original_data', models.JSONField(verbose_name='Données originales')),
                ('deletion_code', models.CharField(max_length=20, unique=True, verbose_name='Code de récupération')),
                ('deleted_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de suppression')),
                ('deletion_reason', models.TextField(blank=True, verbose_name='Raison de la suppression')),
                ('can_restore', models.BooleanField(default=True, verbose_name='Peut être restauré')),
                ('deleted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Supprimé par')),
            ],
            options={
                'verbose_name': 'Élément supprimé',
                'verbose_name_plural': 'Éléments supprimés',
                'ordering': ['-deleted_at'],
            },
        ),
    ]
