# Generated by Django 4.2.24 on 2025-10-26 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deleteditem',
            name='deleted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deleted_items', to=settings.AUTH_USER_MODEL, verbose_name='Supprimé par'),
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('is_deleted', models.BooleanField(default=False, verbose_name='Supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('deletion_reason', models.TextField(blank=True, verbose_name='Raison de la suppression')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('login', 'Connexion'), ('logout', 'Déconnexion'), ('patient_created', 'Patient créé'), ('patient_updated', 'Patient modifié'), ('patient_deleted', 'Patient supprimé'), ('patient_viewed', 'Patient consulté'), ('document_uploaded', 'Document téléchargé'), ('document_updated', 'Document modifié'), ('document_deleted', 'Document supprimé'), ('document_processed', 'Document traité'), ('document_downloaded', 'Document téléchargé'), ('report_created', 'Rapport créé'), ('report_updated', 'Rapport modifié'), ('report_deleted', 'Rapport supprimé'), ('report_approved', 'Rapport approuvé'), ('report_rejected', 'Rapport rejeté'), ('user_created', 'Utilisateur créé'), ('user_updated', 'Utilisateur modifié'), ('user_deleted', 'Utilisateur supprimé'), ('error_occurred', 'Erreur survenue'), ('security_alert', 'Alerte de sécurité')], max_length=50, verbose_name='Action')),
                ('description', models.TextField(verbose_name='Description')),
                ('severity', models.CharField(choices=[('info', 'Information'), ('warning', 'Avertissement'), ('error', 'Erreur'), ('critical', 'Critique')], default='info', max_length=20, verbose_name='Sévérité')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Détails')),
                ('ip_address', models.CharField(blank=True, max_length=45, verbose_name='Adresse IP')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='Agent utilisateur')),
                ('session_key', models.CharField(blank=True, max_length=40, verbose_name='Clé de session')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soft_deleted_objects', to=settings.AUTH_USER_MODEL, verbose_name='Supprimé par')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Activité',
                'verbose_name_plural': 'Activités',
                'ordering': ['-created_at'],
            },
        ),
    ]
