# Generated by Django 4.2.24 on 2025-09-26 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(default='Hôpital EL GHASSANI', max_length=200, verbose_name="Nom de l'hôpital")),
                ('hospital_address', models.TextField(blank=True, verbose_name="Adresse de l'hôpital")),
                ('hospital_phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('hospital_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('maintenance_mode', models.BooleanField(default=False, verbose_name='Mode maintenance')),
                ('max_file_size', models.IntegerField(default=10485760, verbose_name='Taille maximale des fichiers (bytes)')),
                ('allowed_file_types', models.TextField(default='pdf,jpg,jpeg,png,doc,docx', verbose_name='Types de fichiers autorisés')),
                ('session_timeout', models.IntegerField(default=3600, verbose_name="Délai d'expiration de session (secondes)")),
                ('max_login_attempts', models.IntegerField(default=5, verbose_name='Nombre maximum de tentatives de connexion')),
                ('password_min_length', models.IntegerField(default=8, verbose_name='Longueur minimale des mots de passe')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='Notifications par email')),
                ('sms_notifications', models.BooleanField(default=False, verbose_name='Notifications par SMS')),
                ('notification_sound', models.BooleanField(default=True, verbose_name='Son des notifications')),
                ('default_language', models.CharField(choices=[('fr', 'Français'), ('ar', 'العربية'), ('en', 'English')], default='fr', max_length=10, verbose_name='Langue par défaut')),
                ('theme', models.CharField(choices=[('light', 'Clair'), ('dark', 'Sombre'), ('auto', 'Automatique')], default='light', max_length=20, verbose_name='Thème')),
                ('backup_frequency', models.CharField(choices=[('hourly', 'Horaire'), ('daily', 'Quotidien'), ('weekly', 'Hebdomadaire'), ('monthly', 'Mensuel')], default='daily', max_length=20, verbose_name='Fréquence de sauvegarde')),
                ('backup_retention_days', models.IntegerField(default=30, verbose_name='Rétention des sauvegardes (jours)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Paramètre système',
                'verbose_name_plural': 'Paramètres système',
            },
        ),
        migrations.CreateModel(
            name='SettingsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('login', 'Connexion'), ('logout', 'Déconnexion'), ('create', 'Création'), ('update', 'Modification'), ('delete', 'Suppression'), ('export', 'Export'), ('import', 'Import'), ('backup', 'Sauvegarde'), ('restore', 'Restauration'), ('system', 'Système')], max_length=20, verbose_name='Action')),
                ('severity', models.CharField(choices=[('info', 'Information'), ('warning', 'Avertissement'), ('error', 'Erreur'), ('critical', 'Critique')], default='info', max_length=20, verbose_name='Sévérité')),
                ('message', models.TextField(verbose_name='Message')),
                ('details', models.JSONField(blank=True, null=True, verbose_name='Détails')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Log système',
                'verbose_name_plural': 'Logs système',
                'ordering': ['-timestamp'],
            },
        ),
    ]
