# Generated by Django 4.2.24 on 2025-09-26 10:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('report_type', models.CharField(choices=[('consultation', 'Rapport de consultation'), ('surgery', 'Rapport chirurgical'), ('emergency', "Rapport d'urgence"), ('discharge', 'Rapport de sortie'), ('lab_analysis', 'Analyse de laboratoire'), ('radiology', 'Rapport de radiologie'), ('pathology', "Rapport d'anatomopathologie"), ('quality', 'Rapport de qualité'), ('statistics', 'Rapport statistique'), ('other', 'Autre')], max_length=50, verbose_name='Type de rapport')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='Résumé')),
                ('details', models.TextField(blank=True, null=True, verbose_name='Détails')),
                ('patient_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nom du patient')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('pending_review', 'En attente de révision'), ('approved', 'Approuvé'), ('rejected', 'Rejeté'), ('published', 'Publié'), ('archived', 'Archivé')], default='draft', max_length=20, verbose_name='Statut')),
                ('priority', models.CharField(choices=[('low', 'Faible'), ('normal', 'Normal'), ('high', 'Élevé'), ('urgent', 'Urgent'), ('critical', 'Critique')], default='normal', max_length=20, verbose_name='Priorité')),
                ('ai_processed', models.BooleanField(default=False, verbose_name='Traité par IA')),
                ('ai_insights', models.JSONField(blank=True, default=dict, verbose_name='Insights IA')),
                ('ai_recommendations', models.TextField(blank=True, null=True, verbose_name='Recommandations IA')),
                ('ai_confidence', models.FloatField(blank=True, null=True, verbose_name='Confiance IA (%)')),
                ('diagnosis', models.TextField(blank=True, null=True, verbose_name='Diagnostic')),
                ('treatment', models.TextField(blank=True, null=True, verbose_name='Traitement')),
                ('medications', models.JSONField(blank=True, default=list, verbose_name='Médicaments')),
                ('vital_signs', models.JSONField(blank=True, default=dict, verbose_name='Signes vitaux')),
                ('lab_results', models.JSONField(blank=True, default=dict, verbose_name='Résultats de laboratoire')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de révision')),
                ('report_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date du rapport')),
                ('attachments', models.JSONField(blank=True, default=list, verbose_name='Pièces jointes')),
            ],
            options={
                'verbose_name': 'Rapport',
                'verbose_name_plural': 'Rapports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('is_internal', models.BooleanField(default=True, verbose_name='Commentaire interne')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Commentaire de rapport',
                'verbose_name_plural': 'Commentaires de rapports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du modèle')),
                ('report_type', models.CharField(choices=[('consultation', 'Rapport de consultation'), ('surgery', 'Rapport chirurgical'), ('emergency', "Rapport d'urgence"), ('discharge', 'Rapport de sortie'), ('lab_analysis', 'Analyse de laboratoire'), ('radiology', 'Rapport de radiologie'), ('pathology', "Rapport d'anatomopathologie"), ('quality', 'Rapport de qualité'), ('statistics', 'Rapport statistique'), ('other', 'Autre')], max_length=50, verbose_name='Type de rapport')),
                ('template_content', models.JSONField(verbose_name='Contenu du modèle')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Modèle de rapport',
                'verbose_name_plural': 'Modèles de rapports',
                'ordering': ['name'],
            },
        ),
    ]
