# Generated by Django 4.2.24 on 2025-10-07 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='admin_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Commentaires administratifs'),
        ),
        migrations.AddField(
            model_name='report',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_reports', to=settings.AUTH_USER_MODEL, verbose_name='Validé par'),
        ),
        migrations.AddField(
            model_name='report',
            name='validation_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de validation'),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('pending_review', 'En attente de révision'), ('pending_validation', 'En attente de validation'), ('validated', 'Validé'), ('approved', 'Approuvé'), ('rejected', 'Rejeté'), ('published', 'Publié'), ('archived', 'Archivé')], default='draft', max_length=20, verbose_name='Statut'),
        ),
    ]
