# Generated by Django 4.2.24 on 2025-09-26 10:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('document_type', models.CharField(choices=[('prescription', 'Ordonnance'), ('lab_result', 'Résultat de laboratoire'), ('radiology', 'Radiologie'), ('consultation', 'Consultation'), ('surgery', 'Chirurgie'), ('emergency', 'Urgence'), ('discharge', "Sortie d'hôpital"), ('certificate', 'Certificat médical'), ('other', 'Autre')], max_length=50, verbose_name='Type de document')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('file', models.FileField(upload_to='documents/%Y/%m/%d/', verbose_name='Fichier')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='Taille du fichier (bytes)')),
                ('file_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Type de fichier')),
                ('patient_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nom du patient')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours de traitement'), ('completed', 'Terminé'), ('error', 'Erreur'), ('archived', 'Archivé')], default='pending', max_length=20, verbose_name='Statut')),
                ('priority', models.CharField(choices=[('low', 'Faible'), ('normal', 'Normal'), ('high', 'Élevé'), ('urgent', 'Urgent')], default='normal', max_length=20, verbose_name='Priorité')),
                ('ai_processed', models.BooleanField(default=False, verbose_name='Traité par IA')),
                ('ai_confidence', models.FloatField(blank=True, null=True, verbose_name='Confiance IA (%)')),
                ('ai_extracted_text', models.TextField(blank=True, null=True, verbose_name='Texte extrait par IA')),
                ('ai_findings', models.JSONField(blank=True, default=dict, verbose_name='Découvertes IA')),
                ('quality_score', models.PositiveIntegerField(blank=True, null=True, verbose_name='Score de qualité (0-100)')),
                ('processing_time', models.DurationField(blank=True, null=True, verbose_name='Temps de traitement')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de traitement')),
                ('document_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date du document')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nom du tag')),
                ('color', models.CharField(default='#007bff', max_length=7, verbose_name='Couleur (hex)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Tag de document',
                'verbose_name_plural': 'Tags de documents',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentTagRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'association")),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_relations', to='documents.document', verbose_name='Document')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_relations', to='documents.documenttag', verbose_name='Tag')),
            ],
            options={
                'verbose_name': 'Relation Document-Tag',
                'verbose_name_plural': 'Relations Document-Tag',
            },
        ),
    ]
