# Generated by Django 4.2.24 on 2025-09-26 10:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9]+$', 'ID patient doit contenir uniquement des lettres majuscules et des chiffres')], verbose_name='ID Patient')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('ci', models.CharField(max_length=20, unique=True, verbose_name="Carte d'Identité")),
                ('date_of_birth', models.DateField(verbose_name='Date de naissance')),
                ('gender', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin'), ('O', 'Autre')], max_length=1, verbose_name='Genre')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Adresse')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ville')),
                ('blood_type', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, null=True, verbose_name='Groupe sanguin')),
                ('emergency_contact', models.CharField(blank=True, max_length=100, null=True, verbose_name="Contact d'urgence")),
                ('insurance', models.CharField(blank=True, max_length=100, null=True, verbose_name='Assurance')),
                ('allergies', models.TextField(blank=True, null=True, verbose_name='Allergies')),
                ('medical_history', models.TextField(blank=True, null=True, verbose_name='Antécédents médicaux')),
                ('occupation', models.CharField(blank=True, max_length=100, null=True, verbose_name='Profession')),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'Célibataire'), ('married', 'Marié(e)'), ('divorced', 'Divorcé(e)'), ('widowed', 'Veuf/Veuve'), ('separated', 'Séparé(e)')], max_length=20, null=True, verbose_name='État civil')),
                ('status', models.CharField(choices=[('active', 'Actif'), ('inactive', 'Inactif'), ('deceased', 'Décédé'), ('transferred', 'Transféré')], default='active', max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes médicales')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('last_visit', models.DateTimeField(blank=True, null=True, verbose_name='Dernière visite')),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('document_type', models.CharField(max_length=100, verbose_name='Type de document')),
                ('file', models.FileField(upload_to='patient_documents/', verbose_name='Fichier')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Document patient',
                'verbose_name_plural': 'Documents patients',
                'ordering': ['-created_at'],
            },
        ),
    ]
